from pathlib import Path

FILENAME = "sequences/ADA.txt"
MAX_COORD = 44652852   # del header

file_contents = Path(FILENAME).read_text()

lines = file_contents.split("\n")

gene_seq = "".join(lines[1:])   # quitar cabecera

def analyze_exon(number, exon_seq):

    index = gene_seq.find(exon_seq)

    length = len(exon_seq)

    start = MAX_COORD - index
    end   = MAX_COORD - (index + length - 1)

    print(number, " | ", length, " | ", start, " | ", end)

exon1 = "GCTGGCCCCAGGGAAAGCCGAGCGGCCACCGAGCCGGCAGAGACCCACCGAGCGGCGGCGGAGGGAGCAGCGCCGGGGCGCACGAGGGCACCATGGCCCAGACGCCCGCCTTCGACAAGCCCAA"
exon2 = "GTGGAACTGCATGTCCACCTAGACGGATCCATCAAGCCTGAAACCATCTTATACTATGGCAG"
exon3 = "GAGGAGAGGGATCGCCCTCCCAGCTAACACAGCAGAGGGGCTGCTGAACGTCATTGGCATGGACAAGCCGCTCACCCTTCCAGACTTCCTGGCCAAGTTTGACTACTACATGCCTGCTATCGC"
exon4 = "GGGCTGCCGGGAGGCTATCAAAAGGATCGCCTATGAGTTTGTAGAGATGAAGGCCAAAGAGGGCGTGGTGTATGTGGAGGTGCGGTACAGTCCGCACCTGCTGGCCAACTCCAAAGTGGAGCCAATCCCCTGGAACCAGGCTGA"
exon5 = "AGGGGACCTCACCCCAGACGAGGTGGTGGCCCTAGTGGGCCAGGGCCTGCAGGAGGGGGAGCGAGACTTCGGGGTCAAGGCCCGGTCCATCCTGTGCTGCATGCGCCACCAGCCCA"
exon6 = "ACTGGTCCCCCAAGGTGGTGGAGCTGTGTAAGAAGTACCAGCAGCAGACCGTGGTAGCCATTGACCTGGCTGGAGATGAGACCATCCCAGGAAGCAGCCTCTTGCCTGGACATGTCCAGGCCTACCAG"
exon7 = "GAGGCTGTGAAGAGCGGCATTCACCGTACTGTCCACGCCGGGGAGGTGGGCTCGGCCGAAGTAGTAAAAGAG"
exon8 = "GCTGTGGACATACTCAAGACAGAGCGGCTGGGACACGGCTACCACACCCTGGAAGACCAGGCCCTTTATAACAGGCTGCGGCAGGAAAACATGCACTTCGAG"
exon9 = "ATCTGCCCCTGGTCCAGCTACCTCACTGGTGCCTGGAAGCCGGACACGGAGCATGCAGTCATTCG"
exon10 = "GCTCAAAAATGACCAGGCTAACTACTCGCTCAACACAGATGACCCGCTCATCTTCAAGTCCACCCTGGACACTGATTACCAGATGACCAAACGGGACATGGGCTTTACTGAAGAGGAGTTTAAAAGGCTG"
exon11 = "AACATCAATGCGGCCAAATCTAGTTTCCTCCCAGAAGATGAAAAGAGGGAGCTTCTCGACCTGCTCTATAAAGCCTATGGGATGCCACCTTCAGCCTCTGCAG"
exon12 = "GGCAGAACCTCTGAAGACGCCACTCCTCCAAGCCTTCACCCTGTGGAGTCACCCCAACTCTGTGGGGCTGAGCAACATTTTTACATTTATTCCTTCCAAGAAGACCATGATCTCAATAGTCAGTTACTGATGCTCCTGAACCCTATGTGTCCATTTCTGCACACACGTATACCTCGGCATGGCCGCGTCACTTCTCTGATTATGTGCCCTGGCCAGGGACCAGCGCCCTTGCACATGGGCATGGTTGAATCTGAAACCCTCCTTCTGTGGCAACTTGTACTGAAAATCTGGTGCTCAATAAAGAAGCCCATGGCTGGTGGCATGCA"

print("nº | Length |    Start   |    End")
analyze_exon(1, exon1)
analyze_exon(2, exon2)
analyze_exon(3, exon3)
analyze_exon(4, exon4)
analyze_exon(5, exon5)
analyze_exon(6, exon6)
analyze_exon(7, exon7)
analyze_exon(8, exon8)
analyze_exon(9, exon9)
analyze_exon(10, exon10)
analyze_exon(11, exon11)
analyze_exon(12, exon12)